// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/SepMessage.proto

package com.flipkart.yak.sep.proto;

public final class SepMessageProto {
  private SepMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SepTableNameOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes namespace = 1;
    /**
     * <code>required bytes namespace = 1;</code>
     */
    boolean hasNamespace();
    /**
     * <code>required bytes namespace = 1;</code>
     */
    com.google.protobuf.ByteString getNamespace();

    // required bytes qualifier = 2;
    /**
     * <code>required bytes qualifier = 2;</code>
     */
    boolean hasQualifier();
    /**
     * <code>required bytes qualifier = 2;</code>
     */
    com.google.protobuf.ByteString getQualifier();
  }
  /**
   * Protobuf type {@code SepTableName}
   *
   * <pre>
   **
   * Table Name
   * </pre>
   */
  public static final class SepTableName extends
      com.google.protobuf.GeneratedMessage
      implements SepTableNameOrBuilder {
    // Use SepTableName.newBuilder() to construct.
    private SepTableName(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SepTableName(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SepTableName defaultInstance;
    public static SepTableName getDefaultInstance() {
      return defaultInstance;
    }

    public SepTableName getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SepTableName(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              namespace_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              qualifier_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.flipkart.yak.sep.proto.SepMessageProto.internal_static_SepTableName_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.flipkart.yak.sep.proto.SepMessageProto.internal_static_SepTableName_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.class, com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.Builder.class);
    }

    public static com.google.protobuf.Parser<SepTableName> PARSER =
        new com.google.protobuf.AbstractParser<SepTableName>() {
      public SepTableName parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SepTableName(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SepTableName> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes namespace = 1;
    public static final int NAMESPACE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString namespace_;
    /**
     * <code>required bytes namespace = 1;</code>
     */
    public boolean hasNamespace() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes namespace = 1;</code>
     */
    public com.google.protobuf.ByteString getNamespace() {
      return namespace_;
    }

    // required bytes qualifier = 2;
    public static final int QUALIFIER_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString qualifier_;
    /**
     * <code>required bytes qualifier = 2;</code>
     */
    public boolean hasQualifier() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes qualifier = 2;</code>
     */
    public com.google.protobuf.ByteString getQualifier() {
      return qualifier_;
    }

    private void initFields() {
      namespace_ = com.google.protobuf.ByteString.EMPTY;
      qualifier_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNamespace()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQualifier()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, namespace_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, qualifier_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, namespace_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, qualifier_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.flipkart.yak.sep.proto.SepMessageProto.SepTableName)) {
        return super.equals(obj);
      }
      com.flipkart.yak.sep.proto.SepMessageProto.SepTableName other = (com.flipkart.yak.sep.proto.SepMessageProto.SepTableName) obj;

      boolean result = true;
      result = result && (hasNamespace() == other.hasNamespace());
      if (hasNamespace()) {
        result = result && getNamespace()
            .equals(other.getNamespace());
      }
      result = result && (hasQualifier() == other.hasQualifier());
      if (hasQualifier()) {
        result = result && getQualifier()
            .equals(other.getQualifier());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasNamespace()) {
        hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
        hash = (53 * hash) + getNamespace().hashCode();
      }
      if (hasQualifier()) {
        hash = (37 * hash) + QUALIFIER_FIELD_NUMBER;
        hash = (53 * hash) + getQualifier().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.flipkart.yak.sep.proto.SepMessageProto.SepTableName parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepTableName parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepTableName parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepTableName parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepTableName parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepTableName parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepTableName parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepTableName parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepTableName parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepTableName parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.flipkart.yak.sep.proto.SepMessageProto.SepTableName prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SepTableName}
     *
     * <pre>
     **
     * Table Name
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.flipkart.yak.sep.proto.SepMessageProto.SepTableNameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.flipkart.yak.sep.proto.SepMessageProto.internal_static_SepTableName_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.flipkart.yak.sep.proto.SepMessageProto.internal_static_SepTableName_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.class, com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.Builder.class);
      }

      // Construct using com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        namespace_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        qualifier_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.flipkart.yak.sep.proto.SepMessageProto.internal_static_SepTableName_descriptor;
      }

      public com.flipkart.yak.sep.proto.SepMessageProto.SepTableName getDefaultInstanceForType() {
        return com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.getDefaultInstance();
      }

      public com.flipkart.yak.sep.proto.SepMessageProto.SepTableName build() {
        com.flipkart.yak.sep.proto.SepMessageProto.SepTableName result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.flipkart.yak.sep.proto.SepMessageProto.SepTableName buildPartial() {
        com.flipkart.yak.sep.proto.SepMessageProto.SepTableName result = new com.flipkart.yak.sep.proto.SepMessageProto.SepTableName(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.namespace_ = namespace_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.qualifier_ = qualifier_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.flipkart.yak.sep.proto.SepMessageProto.SepTableName) {
          return mergeFrom((com.flipkart.yak.sep.proto.SepMessageProto.SepTableName)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.flipkart.yak.sep.proto.SepMessageProto.SepTableName other) {
        if (other == com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.getDefaultInstance()) return this;
        if (other.hasNamespace()) {
          setNamespace(other.getNamespace());
        }
        if (other.hasQualifier()) {
          setQualifier(other.getQualifier());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNamespace()) {
          
          return false;
        }
        if (!hasQualifier()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.flipkart.yak.sep.proto.SepMessageProto.SepTableName parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.flipkart.yak.sep.proto.SepMessageProto.SepTableName) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes namespace = 1;
      private com.google.protobuf.ByteString namespace_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes namespace = 1;</code>
       */
      public boolean hasNamespace() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes namespace = 1;</code>
       */
      public com.google.protobuf.ByteString getNamespace() {
        return namespace_;
      }
      /**
       * <code>required bytes namespace = 1;</code>
       */
      public Builder setNamespace(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        namespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes namespace = 1;</code>
       */
      public Builder clearNamespace() {
        bitField0_ = (bitField0_ & ~0x00000001);
        namespace_ = getDefaultInstance().getNamespace();
        onChanged();
        return this;
      }

      // required bytes qualifier = 2;
      private com.google.protobuf.ByteString qualifier_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes qualifier = 2;</code>
       */
      public boolean hasQualifier() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes qualifier = 2;</code>
       */
      public com.google.protobuf.ByteString getQualifier() {
        return qualifier_;
      }
      /**
       * <code>required bytes qualifier = 2;</code>
       */
      public Builder setQualifier(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        qualifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes qualifier = 2;</code>
       */
      public Builder clearQualifier() {
        bitField0_ = (bitField0_ & ~0x00000002);
        qualifier_ = getDefaultInstance().getQualifier();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SepTableName)
    }

    static {
      defaultInstance = new SepTableName(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SepTableName)
  }

  public interface SepMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes row = 1;
    /**
     * <code>required bytes row = 1;</code>
     */
    boolean hasRow();
    /**
     * <code>required bytes row = 1;</code>
     */
    com.google.protobuf.ByteString getRow();

    // required uint64 timestamp = 2;
    /**
     * <code>required uint64 timestamp = 2;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required uint64 timestamp = 2;</code>
     */
    long getTimestamp();

    // required bytes value = 3;
    /**
     * <code>required bytes value = 3;</code>
     */
    boolean hasValue();
    /**
     * <code>required bytes value = 3;</code>
     */
    com.google.protobuf.ByteString getValue();

    // required .SepTableName table = 4;
    /**
     * <code>required .SepTableName table = 4;</code>
     */
    boolean hasTable();
    /**
     * <code>required .SepTableName table = 4;</code>
     */
    com.flipkart.yak.sep.proto.SepMessageProto.SepTableName getTable();
    /**
     * <code>required .SepTableName table = 4;</code>
     */
    com.flipkart.yak.sep.proto.SepMessageProto.SepTableNameOrBuilder getTableOrBuilder();

    // optional bytes columnfamily = 5;
    /**
     * <code>optional bytes columnfamily = 5;</code>
     */
    boolean hasColumnfamily();
    /**
     * <code>optional bytes columnfamily = 5;</code>
     */
    com.google.protobuf.ByteString getColumnfamily();

    // optional bytes qualifier = 6;
    /**
     * <code>optional bytes qualifier = 6;</code>
     */
    boolean hasQualifier();
    /**
     * <code>optional bytes qualifier = 6;</code>
     */
    com.google.protobuf.ByteString getQualifier();
  }
  /**
   * Protobuf type {@code SepMessage}
   *
   * <pre>
   **
   * SepMessage
   * </pre>
   */
  public static final class SepMessage extends
      com.google.protobuf.GeneratedMessage
      implements SepMessageOrBuilder {
    // Use SepMessage.newBuilder() to construct.
    private SepMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SepMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SepMessage defaultInstance;
    public static SepMessage getDefaultInstance() {
      return defaultInstance;
    }

    public SepMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SepMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              row_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readUInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              value_ = input.readBytes();
              break;
            }
            case 34: {
              com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = table_.toBuilder();
              }
              table_ = input.readMessage(com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(table_);
                table_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              columnfamily_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              qualifier_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.flipkart.yak.sep.proto.SepMessageProto.internal_static_SepMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.flipkart.yak.sep.proto.SepMessageProto.internal_static_SepMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.flipkart.yak.sep.proto.SepMessageProto.SepMessage.class, com.flipkart.yak.sep.proto.SepMessageProto.SepMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<SepMessage> PARSER =
        new com.google.protobuf.AbstractParser<SepMessage>() {
      public SepMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SepMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SepMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes row = 1;
    public static final int ROW_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString row_;
    /**
     * <code>required bytes row = 1;</code>
     */
    public boolean hasRow() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes row = 1;</code>
     */
    public com.google.protobuf.ByteString getRow() {
      return row_;
    }

    // required uint64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>required uint64 timestamp = 2;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // required bytes value = 3;
    public static final int VALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>required bytes value = 3;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes value = 3;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    // required .SepTableName table = 4;
    public static final int TABLE_FIELD_NUMBER = 4;
    private com.flipkart.yak.sep.proto.SepMessageProto.SepTableName table_;
    /**
     * <code>required .SepTableName table = 4;</code>
     */
    public boolean hasTable() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .SepTableName table = 4;</code>
     */
    public com.flipkart.yak.sep.proto.SepMessageProto.SepTableName getTable() {
      return table_;
    }
    /**
     * <code>required .SepTableName table = 4;</code>
     */
    public com.flipkart.yak.sep.proto.SepMessageProto.SepTableNameOrBuilder getTableOrBuilder() {
      return table_;
    }

    // optional bytes columnfamily = 5;
    public static final int COLUMNFAMILY_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString columnfamily_;
    /**
     * <code>optional bytes columnfamily = 5;</code>
     */
    public boolean hasColumnfamily() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes columnfamily = 5;</code>
     */
    public com.google.protobuf.ByteString getColumnfamily() {
      return columnfamily_;
    }

    // optional bytes qualifier = 6;
    public static final int QUALIFIER_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString qualifier_;
    /**
     * <code>optional bytes qualifier = 6;</code>
     */
    public boolean hasQualifier() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes qualifier = 6;</code>
     */
    public com.google.protobuf.ByteString getQualifier() {
      return qualifier_;
    }

    private void initFields() {
      row_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
      value_ = com.google.protobuf.ByteString.EMPTY;
      table_ = com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.getDefaultInstance();
      columnfamily_ = com.google.protobuf.ByteString.EMPTY;
      qualifier_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRow()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTable()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTable().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, row_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, value_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, table_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, columnfamily_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, qualifier_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, row_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, value_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, table_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, columnfamily_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, qualifier_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.flipkart.yak.sep.proto.SepMessageProto.SepMessage)) {
        return super.equals(obj);
      }
      com.flipkart.yak.sep.proto.SepMessageProto.SepMessage other = (com.flipkart.yak.sep.proto.SepMessageProto.SepMessage) obj;

      boolean result = true;
      result = result && (hasRow() == other.hasRow());
      if (hasRow()) {
        result = result && getRow()
            .equals(other.getRow());
      }
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && getValue()
            .equals(other.getValue());
      }
      result = result && (hasTable() == other.hasTable());
      if (hasTable()) {
        result = result && getTable()
            .equals(other.getTable());
      }
      result = result && (hasColumnfamily() == other.hasColumnfamily());
      if (hasColumnfamily()) {
        result = result && getColumnfamily()
            .equals(other.getColumnfamily());
      }
      result = result && (hasQualifier() == other.hasQualifier());
      if (hasQualifier()) {
        result = result && getQualifier()
            .equals(other.getQualifier());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRow()) {
        hash = (37 * hash) + ROW_FIELD_NUMBER;
        hash = (53 * hash) + getRow().hashCode();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getTimestamp());
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      if (hasTable()) {
        hash = (37 * hash) + TABLE_FIELD_NUMBER;
        hash = (53 * hash) + getTable().hashCode();
      }
      if (hasColumnfamily()) {
        hash = (37 * hash) + COLUMNFAMILY_FIELD_NUMBER;
        hash = (53 * hash) + getColumnfamily().hashCode();
      }
      if (hasQualifier()) {
        hash = (37 * hash) + QUALIFIER_FIELD_NUMBER;
        hash = (53 * hash) + getQualifier().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.flipkart.yak.sep.proto.SepMessageProto.SepMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.flipkart.yak.sep.proto.SepMessageProto.SepMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.flipkart.yak.sep.proto.SepMessageProto.SepMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SepMessage}
     *
     * <pre>
     **
     * SepMessage
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.flipkart.yak.sep.proto.SepMessageProto.SepMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.flipkart.yak.sep.proto.SepMessageProto.internal_static_SepMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.flipkart.yak.sep.proto.SepMessageProto.internal_static_SepMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.flipkart.yak.sep.proto.SepMessageProto.SepMessage.class, com.flipkart.yak.sep.proto.SepMessageProto.SepMessage.Builder.class);
      }

      // Construct using com.flipkart.yak.sep.proto.SepMessageProto.SepMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTableFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        row_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (tableBuilder_ == null) {
          table_ = com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.getDefaultInstance();
        } else {
          tableBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        columnfamily_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        qualifier_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.flipkart.yak.sep.proto.SepMessageProto.internal_static_SepMessage_descriptor;
      }

      public com.flipkart.yak.sep.proto.SepMessageProto.SepMessage getDefaultInstanceForType() {
        return com.flipkart.yak.sep.proto.SepMessageProto.SepMessage.getDefaultInstance();
      }

      public com.flipkart.yak.sep.proto.SepMessageProto.SepMessage build() {
        com.flipkart.yak.sep.proto.SepMessageProto.SepMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.flipkart.yak.sep.proto.SepMessageProto.SepMessage buildPartial() {
        com.flipkart.yak.sep.proto.SepMessageProto.SepMessage result = new com.flipkart.yak.sep.proto.SepMessageProto.SepMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.row_ = row_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (tableBuilder_ == null) {
          result.table_ = table_;
        } else {
          result.table_ = tableBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.columnfamily_ = columnfamily_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.qualifier_ = qualifier_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.flipkart.yak.sep.proto.SepMessageProto.SepMessage) {
          return mergeFrom((com.flipkart.yak.sep.proto.SepMessageProto.SepMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.flipkart.yak.sep.proto.SepMessageProto.SepMessage other) {
        if (other == com.flipkart.yak.sep.proto.SepMessageProto.SepMessage.getDefaultInstance()) return this;
        if (other.hasRow()) {
          setRow(other.getRow());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasTable()) {
          mergeTable(other.getTable());
        }
        if (other.hasColumnfamily()) {
          setColumnfamily(other.getColumnfamily());
        }
        if (other.hasQualifier()) {
          setQualifier(other.getQualifier());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRow()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        if (!hasTable()) {
          
          return false;
        }
        if (!getTable().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.flipkart.yak.sep.proto.SepMessageProto.SepMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.flipkart.yak.sep.proto.SepMessageProto.SepMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes row = 1;
      private com.google.protobuf.ByteString row_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes row = 1;</code>
       */
      public boolean hasRow() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes row = 1;</code>
       */
      public com.google.protobuf.ByteString getRow() {
        return row_;
      }
      /**
       * <code>required bytes row = 1;</code>
       */
      public Builder setRow(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        row_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes row = 1;</code>
       */
      public Builder clearRow() {
        bitField0_ = (bitField0_ & ~0x00000001);
        row_ = getDefaultInstance().getRow();
        onChanged();
        return this;
      }

      // required uint64 timestamp = 2;
      private long timestamp_ ;
      /**
       * <code>required uint64 timestamp = 2;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // required bytes value = 3;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes value = 3;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes value = 3;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>required bytes value = 3;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes value = 3;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // required .SepTableName table = 4;
      private com.flipkart.yak.sep.proto.SepMessageProto.SepTableName table_ = com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.flipkart.yak.sep.proto.SepMessageProto.SepTableName, com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.Builder, com.flipkart.yak.sep.proto.SepMessageProto.SepTableNameOrBuilder> tableBuilder_;
      /**
       * <code>required .SepTableName table = 4;</code>
       */
      public boolean hasTable() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .SepTableName table = 4;</code>
       */
      public com.flipkart.yak.sep.proto.SepMessageProto.SepTableName getTable() {
        if (tableBuilder_ == null) {
          return table_;
        } else {
          return tableBuilder_.getMessage();
        }
      }
      /**
       * <code>required .SepTableName table = 4;</code>
       */
      public Builder setTable(com.flipkart.yak.sep.proto.SepMessageProto.SepTableName value) {
        if (tableBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          table_ = value;
          onChanged();
        } else {
          tableBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .SepTableName table = 4;</code>
       */
      public Builder setTable(
          com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.Builder builderForValue) {
        if (tableBuilder_ == null) {
          table_ = builderForValue.build();
          onChanged();
        } else {
          tableBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .SepTableName table = 4;</code>
       */
      public Builder mergeTable(com.flipkart.yak.sep.proto.SepMessageProto.SepTableName value) {
        if (tableBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              table_ != com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.getDefaultInstance()) {
            table_ =
              com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.newBuilder(table_).mergeFrom(value).buildPartial();
          } else {
            table_ = value;
          }
          onChanged();
        } else {
          tableBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .SepTableName table = 4;</code>
       */
      public Builder clearTable() {
        if (tableBuilder_ == null) {
          table_ = com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.getDefaultInstance();
          onChanged();
        } else {
          tableBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>required .SepTableName table = 4;</code>
       */
      public com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.Builder getTableBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getTableFieldBuilder().getBuilder();
      }
      /**
       * <code>required .SepTableName table = 4;</code>
       */
      public com.flipkart.yak.sep.proto.SepMessageProto.SepTableNameOrBuilder getTableOrBuilder() {
        if (tableBuilder_ != null) {
          return tableBuilder_.getMessageOrBuilder();
        } else {
          return table_;
        }
      }
      /**
       * <code>required .SepTableName table = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.flipkart.yak.sep.proto.SepMessageProto.SepTableName, com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.Builder, com.flipkart.yak.sep.proto.SepMessageProto.SepTableNameOrBuilder> 
          getTableFieldBuilder() {
        if (tableBuilder_ == null) {
          tableBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.flipkart.yak.sep.proto.SepMessageProto.SepTableName, com.flipkart.yak.sep.proto.SepMessageProto.SepTableName.Builder, com.flipkart.yak.sep.proto.SepMessageProto.SepTableNameOrBuilder>(
                  table_,
                  getParentForChildren(),
                  isClean());
          table_ = null;
        }
        return tableBuilder_;
      }

      // optional bytes columnfamily = 5;
      private com.google.protobuf.ByteString columnfamily_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes columnfamily = 5;</code>
       */
      public boolean hasColumnfamily() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes columnfamily = 5;</code>
       */
      public com.google.protobuf.ByteString getColumnfamily() {
        return columnfamily_;
      }
      /**
       * <code>optional bytes columnfamily = 5;</code>
       */
      public Builder setColumnfamily(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        columnfamily_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes columnfamily = 5;</code>
       */
      public Builder clearColumnfamily() {
        bitField0_ = (bitField0_ & ~0x00000010);
        columnfamily_ = getDefaultInstance().getColumnfamily();
        onChanged();
        return this;
      }

      // optional bytes qualifier = 6;
      private com.google.protobuf.ByteString qualifier_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes qualifier = 6;</code>
       */
      public boolean hasQualifier() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes qualifier = 6;</code>
       */
      public com.google.protobuf.ByteString getQualifier() {
        return qualifier_;
      }
      /**
       * <code>optional bytes qualifier = 6;</code>
       */
      public Builder setQualifier(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        qualifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes qualifier = 6;</code>
       */
      public Builder clearQualifier() {
        bitField0_ = (bitField0_ & ~0x00000020);
        qualifier_ = getDefaultInstance().getQualifier();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SepMessage)
    }

    static {
      defaultInstance = new SepMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SepMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SepTableName_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SepTableName_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SepMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SepMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/proto/SepMessage.proto\"4\n\014Sep" +
      "TableName\022\021\n\tnamespace\030\001 \002(\014\022\021\n\tqualifie" +
      "r\030\002 \002(\014\"\202\001\n\nSepMessage\022\013\n\003row\030\001 \002(\014\022\021\n\tt" +
      "imestamp\030\002 \002(\004\022\r\n\005value\030\003 \002(\014\022\034\n\005table\030\004" +
      " \002(\0132\r.SepTableName\022\024\n\014columnfamily\030\005 \001(" +
      "\014\022\021\n\tqualifier\030\006 \001(\014B2\n\032com.flipkart.yak" +
      ".sep.protoB\017SepMessageProtoH\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SepTableName_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SepTableName_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SepTableName_descriptor,
              new java.lang.String[] { "Namespace", "Qualifier", });
          internal_static_SepMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_SepMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SepMessage_descriptor,
              new java.lang.String[] { "Row", "Timestamp", "Value", "Table", "Columnfamily", "Qualifier", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
